---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.19.5

inputs:
  - name: dp-nlp-hub

outputs:
  - name: build

caches:
  - path: go/

run:
  path: dp-nlp-hub/ci/scripts/build.sh
